"""add column

Revision ID: f6b02bf3f809
Revises: cf54caaeff1f
Create Date: 2024-03-15 16:47:54.327464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b02bf3f809"
down_revision: Union[str, None] = "cf54caaeff1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fields", sa.Column("created", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "created")
    # ### end Alembic commands ###
