"""add column is_complete

Revision ID: 9bc12d192d04
Revises: f6b02bf3f809
Create Date: 2024-03-15 18:31:09.152901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bc12d192d04"
down_revision: Union[str, None] = "f6b02bf3f809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields", sa.Column("is_complete", sa.Boolean(), nullable=False, default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "is_complete")
    # ### end Alembic commands ###
